[workspace]
members = [
    "crates/ruid-camera", "crates/ruid-detect",
    "crates/ruid-preprocess",
    "crates/ruid-detect"
    ]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
