[package]
name = "ru_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
tract-onnx = { workspace = true }
ndarray = { workspace = true }
opencv = { workspace = true }
thiserror = { workspace = true }
num_cpus = "1.16.0"
